name: Install Project Requirements
description: Install requirements from a PEP 517 project

inputs:
  requirements:
    description: "Whitespace-delimited list of project requirements to install."
    required: true
  project-root:
    description: "The filesystem path to the root of the project to install from; defaults to github.workspace."
    default: ${{ github.workspace }}
  extra:
    description: "Name of the optional dependencies marker; e.g. dev."
    required: false
    default: ""
  workflow-repo:
    # Only needed for PRs in other repos wanting to test new workflow changes before they are merged.
    # These inputs should not be specified by another repo on their main branch.
    description: "The repo to use to run additional workflows and actions."
    default: "beeware/.github"
  workflow-repo-ref:
    description: "The repo ref to use to run additional workflows and actions."
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout ${{ inputs.workflow-repo }}${{ inputs.workflow-repo-ref && format('@{0}', inputs.workflow-repo-ref) || '' }}
      uses: actions/checkout@v4.1.6
      with:
        repository: ${{ inputs.workflow-repo }}
        ref: ${{ inputs.workflow-repo-ref }}
        path: .github-beeware

    - name: Resolve Project Root
      id: paths
      shell: bash
      run: echo "project-root=$(cd "${{ inputs.project-root }}"; pwd -P)" | tee -a ${GITHUB_OUTPUT}

    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools build wheel

    - name: Install Requirements
      working-directory: ./.github-beeware/scripts
      shell: bash
      run: |
        python -m install_requirement ${{ inputs.requirements }} \
          ${{ inputs.extra && format('--extra "{0}"', inputs.extra) || '' }} \
          --project-root "$(printf -- "%q" "${{ steps.paths.outputs.project-root }}")"
