name: PR Body Parse
description: Parse a value from the body of the relevant PR for a specific key

inputs:
  key-regex:
    description: "The regex for the key identifying the value to return, e.g. BRIEFCASE[-_]*REPO"
    required: true
  testing-pr-body:
    description: "Override value for body of PR; only for testing."
    required: false

outputs:
  extracted-value:
    value: ${{ steps.parse.outputs.extracted-value }}
    description: "The value extracted from the PR's body for the specified key."

runs:
  using: composite
  steps:
    - name: Parse PR Body for ${{ inputs.key-regex }}
      id: parse
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        # Retrieve PR Body (only PRs will have a value for github.event.pull_request.number)
        PR_BODY="${{ inputs.testing-pr-body }}"
        if [[ -z "${PR_BODY}" && -n "${{ github.event.pull_request.number }}" ]]; then
          PR_BODY=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.body')
        fi
        printf "::group::Retrieved PR Body\n%s\n::endgroup::\n" "${PR_BODY}"

        # Parse value with given regex
        EXTRACTED_VALUE=$(printf "%s" "${PR_BODY}" | perl -wlne '/${{ inputs.key-regex }}:\s*\K\S+/i and print $&')

        # Expose value as an output
        printf -- "extracted-value=%s\n" "${EXTRACTED_VALUE}" | tee -a ${GITHUB_OUTPUT}
